name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code #toma los archivos del repositorio
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t felipercz/docker-graph:1.0.1 .
        docker build -t felipercz/docker-graph:latest . 
        
    - name: Push Docker Image
      run: |
        docker push felipercz/docker-graph:1.0.1
        docker build -t felipercz/docker-graph:latest . 
        
      
    
      
